no=int(input('Enter day number'))
if(no==1)
	print('monday')
else if(no==2)
	print('tuesday')
else if(no==3)
	print('wednesday')
else if(no==4)
	print('thursday')
else if(no==5)
	print('friday')
else if(no==6)
	print('saturday')
else if(no==7)
	print('sunday')
